version: "3.3"

services:
    nginx:
        build: .
        ports:
            - 80:80
            - 443:443
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt:ro
            - /tmp/acme_challenge:/tmp/acme_challenge
